version: '3.8'

services:
  mongo:
    image: mongo:4.4.9
    restart: always
    volumes:
      - ./data:/data/db

  api:
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/crud-api
    depends_on:
      - mongo